# version: '3.9'

# services:
#   db:
#     image: postgres:14
#     container_name: postgres_db
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: credit_system
#     ports:
#       - '5432:5432'

#   web:
#     build: .
#     container_name: django_app
#     command: python app/main.py
#     ports:
#       - '8000:8000'
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgres://user:password@db:5432/credit_system

version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: credit_system
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d credit_system']
      interval: 5s
      timeout: 10s
      retries: 5

  web:
    build: .
    container_name: django_app
    command: python app/main.py
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@db:5432/credit_system
    entrypoint: ['/bin/sh', '-c', 'sleep 5 && python app/main.py'] # Add a 5-second delay
